name: Portainer(CN) Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  frontfile: 'front-public.tar.gz'
  node-version: '16.13.2'
  go-version: '>=1.17.0'

jobs:  
  build:  
    runs-on: ubuntu-latest
        
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
          
      - name: Install yarn 
        run: npm i -g yarn
       
      - name: Install dependencies
        run: yarn -i
      
      - name: Build source
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
        run: go version && yarn start

      - name: Packagin front...
        run: tar -zcvf ${{ env.frontfile }} -C ./dist/ public
        
      - name: Read package.json
        id: version
        uses: tyankatsu0105/read-package-version-actions@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker
        id: docker
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          file: ./build/linux/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            bigbugcc/portainer-ce:latest
            bigbugcc/portainer-ce:v${{ steps.version.outputs.version }}
      
      - name: Image digest
        run: echo ${{ steps.docker.outputs.digest }}
        
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Portainer front(CN) - v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body: |
            Release Note:
            - 前端若干汉化补充 
            - [ DockerHub🐬 ](https://hub.docker.com/r/bigbugcc/portainer)
          files: |
            ${{ env.frontfile }}
            
